### ISSUE TITLE
Publishing @webref/idl not possible if only IDL has changed

### ISSUE THREAD

**Issue by foolip** [w3c/webref#109]
Running `npx lerna diff` doesn't show the diff against the published package but against what's in Git, and the IDL files in `packages/idl/` are not checked in. As a result, `npx lerna publish` refuses to do anything if only the IDL files have changed, which will be very common.

I haven't been able to find a workaround. Should we just check in the patched files in `packages/idl/`?

**Comment by foolip** [comment]
This is an issue now, since there have been some changes to IDL but there's no other unrelated change I can think of making to get around the problem.

@dontcallmedom @tidoust thoughts?

**Comment by tidoust** [comment]
I would prefer not to check in the patched files. As we add other packages over time, that may mean lots of mostly duplicate content in the repo. Or rather, I would prefer to avoid checking in the patched files with a strong association with a given package, (i.e. I would put them under `ed/idlpatched` or even use the patches to produce `ed/idl`, and not have them under `packages/idl/`) as we may want to include them in some other package as well afterwards... but I suspect that this is precisely what is not possible?

Different possibilities:
- I see `lerna` has a [`--force-publish` option](https://github.com/lerna/lerna/tree/main/commands/version#--force-publish). One possibility would be to determine whether IDL changed, running the diff ourselves somehow, and trigger `npx lerna publish --force-publish` when needed. That's far from ideal: detecting diff is one of the things that we'd like lerna to tell us!
- Another possibility would be to use another branch or another repo for the publication to keep the contents of the main branch somewhat sane.
- Or we check in the patched files after all, because that's easier and aligned with how lerna works...

**Comment by foolip** [comment]
Huh, I had been looking for something like `--force-publish` but couldn't find anything as it's not mentioned in `npx lerna publish --help`. But I just tested it now and published 1.0.4, so this works!

What I do to check if there's any need to release is `git diff @webref/idl@1.0.3 ed/idl`. If there are any changes there and the tests still pass, then the release will at least not be identical. But perhaps it's unnecessary to release if there are only whitespace changes :)

**Comment by tidoust** [comment]
Closing issue since `--force-publish` seems to do the trick, noting we'll have to add the diff check when we automate the release process.
