### ISSUE TITLE
Move “<color>” “values” to “<named-color>”

### ISSUE THREAD

**Issue by SofyaPovarova** [w3c/webref#1093]
Should the values of “\<color\>” from [css-color.json](https://github.com/w3c/webref/blob/curated/ed/css/css-color.json) be moved to “\<named-color\>”? According to the[ spec](https://drafts.csswg.org/css-color-4/#typedef-named-color), they should belong to “\<named-color\>”.
Current state:
```
{
"name": "<color>",
"prose": "Colors in CSS are represented by the <color> type:",
"type": "type",
"value": "<absolute-color-base> | currentcolor | <system-color>",
"values": [
        {
          "name": "aliceblue",
          "type": "value",
          "value": "aliceblue"
        },
        {
          "name": "antiquewhite",
          "type": "value",
          "value": "antiquewhite"
        },
        {
          "name": "aqua",
          "type": "value",
          "value": "aqua"
        },
        {
          "name": "aquamarine",
          "type": "value",
          "value": "aquamarine"
        }
	.......
]
},
{
      "name": "<named-color>",
      "prose": "CSS defines a large set of named colors, so that common colors can be written and read more easily. A <named-color> is written as an <ident>, accepted anywhere a <color> is. As usual for CSS-defined <ident>s, all of these keywords are ASCII case-insensitive.",
      "type": "type"
}
```
Suggested change:
```
{
     "name": "<color>",
     "prose": "Colors in CSS are represented by the <color> type:",
      "type": "type",
      "value": "<absolute-color-base> | currentcolor | <system-color>"
},
{
      "name": "<named-color>",
      "prose": "CSS defines a large set of named colors, so that common colors can be written and read more easily. A <named-color> is written as an <ident>, accepted anywhere a <color> is. As usual for CSS-defined <ident>s, all of these keywords are ASCII case-insensitive.",
      "type": "type",
      "values": [
       {
          "name": "aliceblue",
          "type": "value",
          "value": "aliceblue"
        },
        {
          "name": "antiquewhite",
          "type": "value",
          "value": "antiquewhite"
        },
        {
          "name": "aqua",
          "type": "value",
          "value": "aqua"
        },
        {
          "name": "aquamarine",
          "type": "value",
          "value": "aquamarine"
        }
	    .......
]
}
```

As well as with the previous issue, I’d be happy to submit a pull request if this change makes sense.
Thank you!

**Comment by tidoust** [comment]
The reason why named colors are associated with `<color>` and not with `<named-color>` in Webref is precisely because that is what the specification defines in its markup. For instance, [`aliceblue`](https://drafts.csswg.org/css-color-4/#valdef-color-aliceblue) is defined with:

```html
<dfn class="css" data-dfn-for="<color>"
    data-dfn-type="value" data-export=""
    id="valdef-color-aliceblue">
  aliceblue
</dfn>
```

The `data-dfn-for` attribute scopes the definition to `<color>` in particular.

That attribute is set this way because the [source of the spec](https://github.com/w3c/csswg-drafts/blob/7b47e34149ad548e03b81fc2b86420d176e48789/css-color-4/Overview.bs#L1423C50-L1423C50) sets a similar `dfn-for` attribute in the wrapping table, which applies to all the definitions it contains:

```html
<table class="named-color-table" dfn-type=value dfn-for="<color>">
```

It that attribute was changed to `dfn-for="<named-color>"` (or possibly to `dfn-for="<color>,<named-color>"` if both seem important), you would get what you want in Webref. So... pull request, yes! But against https://github.com/w3c/csswg-drafts if possible!

**Comment by SofyaPovarova** [comment]
Thank you! Now it's clear what should I do :)
