### ISSUE TITLE
The definition of `font-width` is missing from ED CSS Fonts (4)

### ISSUE THREAD

**Issue by cdoublev** [w3c/webref#1130]
In https://github.com/w3c/csswg-drafts/commit/b0660ee070c55cc9b2669498460fc0210d105403, the CSS property `font-stretch` was renamed to `font-width` in the ED of CSS Fonts 4, and `font-stretch` became a legacy alias of `font-width`.

But `ed/css/css-fonts.json` still does not include the definition of `font-width`, 2 days after this change. 

I do not mind waiting several days for the definitions to mirror what is actually included online in the specs, but I suspect there is a problem because, in my experience, a change that becomes visible in the spec is usually reflected in the next crawl.

**Comment by tidoust** [comment]
There seems to be a problem indeed, see the [error in the crawl result](https://github.com/w3c/webref/blob/0f69fd9b4664ed895ec96144510a43002b8bc5ca/ed/index.json#L18262C7-L18262C15), I'll look into it. Thanks for the report!

I also created #1131 to add a notification mechanism. The crawler records the error and reuses previous extracts when a problem occurs, which is nice but also hides the error...

**Comment by tidoust** [comment]
Crash is due to an empty line at the end of [the table that defines `font-style`](https://drafts.csswg.org/css-fonts-4/#font-style-prop).

I do not know how that empty line ended up in there. I suspect that is triggered by the HTML comment that exists in the source, but then that comment has been around for years, and re-generating the spec with the lastest version of Bikeshed does not seem to produce that empty line. There have been various code updates made to Bikeshed in the past couple of days, perhaps the spec got generated with an intermediary version.

Anyway, I'll make code extraction ignore empty lines to avoid crashes!

**Comment by cdoublev** [comment]
Ah, I forgot to check that crawl result, sorry. You spotted the problem way quicker than I could have though.

  > re-generating the spec with the lastest version of Bikeshed does not seem to produce that empty line

Did you check with the [online tool](https://api.csswg.org/bikeshed/) or with a local install? I do not know if the former uses the latest version.

Thank you!

**Comment by tidoust** [comment]
> Did you check with the [online tool](https://api.csswg.org/bikeshed/) or with a local install? I do not know if the former uses the latest version.

Both ;) But I had somehow failed to update my local install. Problem reported to Bikeshed!

Webref's data now updated with the new `font-weight` property.

The css-fonts-4 spec is still "broken" in the sense that it does not define the previous `font-stretch` property with the right definition type (links to `font-stretch` end up linking to the /TR version as a result). I'll report that as well.
