### ISSUE TITLE
Release @webref/idl every Monday

### ISSUE THREAD

**Issue by foolip** [w3c/webref#123]
Per https://github.com/w3c/browser-specs/pull/252#issuecomment-793884959 it would be great to arrange to @webref/idl releases on Mondays.

@dontcallmedom @tidoust what would a process for this look like? If we have steps written down for how to do the release, could we take turns doing it, or even automate? Do you automatically publishing any other NPM packages?

**Comment by foolip** [comment]
Releasing on Thursday would actually be great and is what I originally wanted to suggest before https://github.com/w3c/browser-specs/pull/252#issuecomment-793884959. This is because BCD is released every Thursday, and it makes sense to depend on BCD and `@webref/idl` together, which is what mdn-bcd-collector does. The update PRs for both should then come on Friday, which would be convenient.

If we don't both with automating releases for now, what steps should a human follow to determine if a release is warranted, and which part of the version should be bumped?

**Comment by tidoust** [comment]
Ideally, a semi-automated release process could be:
1. A job runs every Thursday and creates a PR that updates the version in `packages/idl/package.json` and details the expected diff in the body of the PR description. Default would probably be to increase the `patch` part of the version number. If the job fails, e.g. because a patch is no longer valid, it should rather create an issue.
2. One of us reviews the PR, checks the diff, checks the need to release a minor / major version instead.
3. When the PR is merged, another job reacts to the version increment in `packages/idl/package.json`, and creates the release and publishes the package.

I'm not sure to what extent lerna is needed with that approach. As far as I can tell, it would only take care of tagging the release and publishing the package, which may also be done with a couple of Git and npm commands.

**Comment by foolip** [comment]
@tidoust that sounds pretty good to me.

A non-trivial bit is creating a diff of the changes, since the previous state is only in an NPM package. Do we install a copy of the most recent package, and diff against that?

**Comment by foolip** [comment]
I discovered in https://github.com/w3c/webref/pull/129#issuecomment-797374120 that publishing using `npx lerna publish --force-publish` no longer works when we have two packages, as both must then be updated, so I had to do it manually. So we'll have no use for Lerna at all I think.

**Comment by saschanaz** [comment]
Is there any remaining work item here?

**Comment by foolip** [comment]
No, this is done. Thanks @tidoust!
