### ISSUE TITLE
No json shows `anchor-size()` can be used as value for sizing properties

### ISSUE THREAD

**Issue by OnkarRuikar** [w3c/webref#1312]
LIke [`stretch` and `fit-content` values](https://github.com/w3c/webref/blob/4b979577849548279e3fdafca2486911ddf10efd/ed/css/css-sizing-4.json#L9) the `css-anchor-position-1.json` needs to show `width` and other properties take `anchor-size()` as value.

**Comment by tidoust** [comment]
As [done in css-sizing-4](https://drafts.csswg.org/css-sizing-4/#sizing-values), css-anchor-position would ideally list the impacted CSS properties in a table with a "New Values" row instead of [only saying so in prose](https://drafts.csswg.org/css-anchor-position-1/#sizing).

On top of allowing the crawler to report that information automatically in the extract, this would help clarify what exact properties can take `anchor-size()` as value. For example, the prose links to the definition of [sizing properties](https://drafts.csswg.org/css-sizing-3/#sizing-property) in css-sizing-3, which has a note that targets [css-logical-1](https://drafts.csswg.org/css-logical-1/). Can `anchor-size()` also be used with the flow-relative properties defined in css-logical-1? (Or maybe that just does not make any sense?)

Also, if I'm reading things correctly, it seems the CSS WG resolved to extend the list of properties on which `anchor-size()` could be used not long ago, see https://github.com/w3c/csswg-drafts/issues/9827#issuecomment-2160430157.

If there's an issue opened against the spec, we could add a CSS patch to add "New values" entries in the css-anchor-position CSS extract (we try to always associate patches with issues so that we know when to drop it).

**Comment by OnkarRuikar** [comment]
> Can `anchor-size()` also be used with the flow-relative properties defined in css-logical-1?

It looks like [it does](https://developer.mozilla.org/en-US/play?id=uJW7g%2FMbXqtgWUDiMLM84%2BMFw%2F3txb5J2Mz8bvTyrUEjc61RsIVn75eJl9QNo%2B8rsVu23%2B6YrtuAH3O8).

**Comment by OnkarRuikar** [comment]
> If there's an issue opened against the spec, we could add a CSS patch to add "New values" entries in the css-anchor-position CSS extract (we try to always associate patches with issues so that we know when to drop it).

We do not need a patch now. After the requested spec update, the values are [reflected in the webref](https://github.com/w3c/webref/blob/ff83d54c5b96041dfccd6d0b0363163e6f06f68e/ed/css/css-anchor-position.json#L127-L151). If you feel the changes are right then please close the issue.

**Comment by tidoust** [comment]
Great, thanks for reporting the issue!
