### ISSUE TITLE
Why do we have css-images-4.idl but no css-images.idl?

### ISSUE THREAD

**Issue by foolip** [w3c/webref#173]
We have `css-animations-2.idl` because there's also a `css-transitions.idl`, but why `css-images-4.idl` on its own? Can this be avoided?

**Comment by tidoust** [comment]
That's the same rule in practice. CSS Images 4 is [defined in browser-specs as a delta spec](https://github.com/w3c/browser-specs/blob/master/specs.json#L343), so the IDL extract uses the spec shortname, and not the series shortname. There is no `css-images.idl` file because CSS Images 3 does not define any IDL.

The rule could be amended to use the series shortname when the non-delta version of the spec does not define any IDL.

**Comment by foolip** [comment]
OK, so I see both `ed/css/css-images.json` and `ed/css/css-images-4.json` exist, then I don't see how else we could do this. Sorry for the noise.
