### ISSUE TITLE
Crypto interface incorrectly classified as non-normative

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webref#329]
citing {{Crypto}} over on:
https://github.com/wicg/uuid

It seems the Crypto interface is misclassified as non-normative. Do we need to override that somehow in WebRef? Or can we make a sneaky fix to markup of the TR document to fix that?

**Comment by tidoust** [comment]
The problem is in the ED, not really in the /TR version.

The term "misclassified" makes it sound as if Webref is where the error is, but the problem is that the `<dfn>` appears in a section marked as non normative in the ED:
https://w3c.github.io/webcrypto/#Crypto-description

I reported that issue a few months ago:
https://github.com/w3c/webcrypto/issues/252

The problem got fixed in the actual source of the spec:
https://github.com/w3c/webcrypto/blob/master/spec/Overview.html#L786

Problem is that the `gh-pages` branch seems to have last been updated 9 months ago, so the ED is not the latest draft.

**Comment by marcoscaceres** [comment]
Ah, my bad. I thought Web Crypto was a Rec. I should have checked more closely. I’ll fix that.

**Comment by marcoscaceres** [comment]
Fixed! https://w3c.github.io/webcrypto/ 😁😁😁 now on "auto-publish".
