### ISSUE TITLE
`selector()` should be defined in prose

### ISSUE THREAD

**Issue by cdoublev** [w3c/webref#333]
[The CSS type `selector()`](https://github.com/w3c/webref/blob/7d1a1852ccfe450925a14a3de164c16e2c914f71/ed/css/scroll-animations.json#L43) from [Scroll Animation 1](https://drafts.csswg.org/scroll-animations-1/#valdef-scroll-timeline-source-selector)  is extracted as: 

```
"<selector()>": {
  "value": "selector()",
},
``` 
I think it should be read as written in `prose` with the value `'The scroll container identified by the <id-selector>.'` I didn't dive very deep to understand why, but I guess that a `production css` anchor is missing in the specification. Let me know if I should report this issue in the draft specs repo instead (or if you're willing to).

**Comment by tidoust** [comment]
Extraction could perhaps add prose for value spaces but the initial goal is more to extract production rules whenever possible and prose only when there aren't any. In this case, I would rather expect to see:

```
"<selector()>": {
  "value": "selector(<id-selector>)"
},
```

... meaning a function type named `selector()` that defines a function `selector` that takes an argument of type `<id-selector>`.

The problem is that the way that `selector()` is used and defined in the spec is slightly inconsistent with the way such functions get defined in other CSS specs. The `<dt>` element should include the function arguments in particular, meaning text content should rather be `selector(<id-selector>)`.

That said, fixing the `<dt>` element would not be enough to create a fantastically useful value space entry because nothing references that `<selector()>` definition in practice. The `<element-offset>` definition includes its own definition of `selector()` but does not reference the definition itself. It would if its definition rather was: `<selector()> [<element-offset-edge> || <number>]?` (which would arguably be more consistent with how other CSS specs handle such situations).

I note that the [`<supports-selector-fn>` value space](https://drafts.csswg.org/css-conditional-4/#typedef-supports-selector-fn) definition in CSS Conditional Rules Level 4 uses a `selector()` definition as well... but a different one, so updating the definition in Scroll-linked Animations 1 as suggested above would create another question on what the actual definition of `<selector()>` should be when you consider specs together.

Extraction rules could be made smart enough to skip over, or warn about, value space definitions that are not referenced.

**Comment by cdoublev** [comment]
Thanks for looking at the related definition values. It seems wiser to wait for those specs to become more consistent than to open issues to suggest change(s).

I would also prefer to get the syntax value, obviously.

From the perspective of a CSS parser implementer in which a list of definition and initial property values is generated using your library, a prose in place of a missing syntax value saves a bit of time that corresponds to finding the spec URL and figuring out what the syntax value should be by reading the spec. Then the prose is no longer usefull to me.

From the perspective of a CSS documentation (like CSSTree Syntax Reference) reader, the prose always remains usefull.

**Comment by cdoublev** [comment]
Closing in favour of https://github.com/w3c/reffy/issues/971.
