### ISSUE TITLE
Automate minor package version bump when new/deleted files are detected

### ISSUE THREAD

**Issue by tidoust** [w3c/webref#341]
See suggestion in https://github.com/w3c/webref/pull/332#issuecomment-911650606

What makes it a bit tricky is that the minor version bump must happen before the pre-release PR gets created and not be done in the pre-release PR itself (the pre-release PR bumps the version number as well, but the resulting version is not what gets released). In other words, instead of created the pre-release PR, the workflow should create a PR that bumps the minor part of the version.

If a pre-release PR already existed, the workflow should close it as long as the version needs to be bumped.

Alternatively, the workflow could perhaps bump the version directly.

**Comment by dontcallmedom** [comment]
thinking some more about it, wouldn't it be simpler to have the reffy-update workflow do the bump?

`git ls-files --other --directory --exclude-standard ` allows to find new files. 

I guess for deleted files, we should probably couple it to the clean-up abandoned files workflow ", since `git ls-files --deleted --directory --exclude-standard` would probably generate false bumps in case of crawling errors.
