### ISSUE TITLE
Buggy idlnames extract for Web Animations

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webref#459]
The current IDL extracts for the following names only list partial interfaces from Web Animations 2, without their main definition from Web Animations 1: 
[Animation](https://github.com/w3c/webref/tree/main/ed/idlnames/Animation.idl)
[AnimationTimeline](https://github.com/w3c/webref/tree/main/ed/idlnames/AnimationTimeline.idl)
[AnimationEffect](https://github.com/w3c/webref/tree/main/ed/idlnames/AnimationEffect.idl)
[EffectTiming](https://github.com/w3c/webref/tree/main/ed/idlnames/EffectTiming.idl)
[ComputedEffectTiming](https://github.com/w3c/webref/tree/main/ed/idlnames/ComputedEffectTiming.idl)

In addition to fixing the extracts, we should probably add a validation check to make sure no partial can be defined without a matching main interface.

**Comment by tidoust** [comment]
> In addition to fixing the extracts, we should probably add a validation check to make sure no partial can be defined without a matching main interface.

I believe that validation check is done after curation: https://github.com/w3c/webref/blob/main/test/idl/consistency.js#L316
(test fails if partials remain after merge).

**Comment by tidoust** [comment]
> The current IDL extracts for the following names only list partial interfaces from Web Animations 2, without their main definition from Web Animations 1

I think that this is just a transient error due to the fact that the last crawl of Web Animations 1 yielded a page with a "500 Internal Server Error" title: https://github.com/w3c/webref/blob/a1f1e043bb4e9d269588cba52760a732ce851e43/ed/index.json#L20654

In other words, no Web IDL could be extracted from Web Animations 1 (we just preserved the IDL extract because we only delete files from the repo manually), and the `idlnames` extract was generated without the Web IDL from Web Animations 1 as a result.

The `idlnames` extract would be correct if crawl succeeds, as evidenced by the tr version, for which crawl succeeded: https://github.com/w3c/webref/blob/a1f1e043bb4e9d269588cba52760a732ce851e43/tr/idlnames/Animation.idl

**Comment by dontcallmedom** [comment]
I thought I had checked that, but obviously got it wrong (maybe because I initially thought this was linked to CSS Animation, rather than Web Animations); sorry for the noise then :)
