### ISSUE TITLE
Idle Detection is not indexed

### ISSUE THREAD

**Issue by annevk** [w3c/webref#56]
If it were in WPT `/interfaces/` we could use `idl_test()` rather than some custom wrapper.

cc @foolip

**Comment by tidoust** [comment]
If I'm [looking at the right repo](https://github.com/WICG/idle-detection/), the problem is that there is no "proper" spec to parse. The spec is the README, and the crawler cannot parse markdown files.

Markdown files lack the semantics the crawl would need to extract definitions and the like. It may still be possible to extract the IDL index by looking at code blocks that can be parsed as IDL though.

**Comment by annevk** [comment]
Thanks for taking a look. I learned about another way to solve this in WPT so I guess I'll close this for now.
