### ISSUE TITLE
Handle CSS value spaces rgb() and hsl() with second "legacy" definition

### ISSUE THREAD

**Issue by tidoust** [w3c/webref#563]
[`<rgb()>`](https://drafts.csswg.org/css-color-4/#rgb-functions) and [`<hsl()>`](https://drafts.csswg.org/css-color-4/#the-hsl-notation) are defined with a legacy syntax that `@webref/css` does not extract. The legacy syntax defines a comma separated list of arguments while the modern syntax defines a whitespace/slash separated list. The legacy syntax will never be removed, I presume, and I would bet many CSS authors use the legacy syntax instead of the new one.

```html
<!-- Markup for the modern syntax -->
<pre class="prod highlight">
    <dfn class="dfn-paneled" data-dfn-type="function" data-export="" id="funcdef-hsl">
        <c- nf="">hsl</c-><c- p="">()</c->
    </dfn>
    <!-- ... -->
</pre>
<!-- Markup for the legacy syntax -->
<pre class="prod highlight">
    <c- nf="">hsl</c-><c- p="">()</c->
    <!-- ... -->
</pre>
```

I'm not sure what to suggest and where to suggest it. I believe that Bikeshed should allow defining a legacy syntax that `@webref/css` could assign to an additional `legacy` for an entry in `valuespace`, but to my knowledge, these are the only types that have two value definitions defined in the same spec.

_Originally posted by @cdoublev in https://github.com/w3c/webref/issues/306#issuecomment-1102438690_

**Comment by cdoublev** [comment]
I have a preference for `legacyValue` because rewriting `modern` to `modern | legacy` would result to a different parse tree: `Or(Terminal('modern'), Terminal('legacy'))` vs `Terminal('modern')`. The 2nd solution could make a difference when the parse tree must be read from bottom to top, and a CSS grammar parser must have some sort of fallback mechanism anyway, eg. to handle math functions like `<calc()>` that can replace numeric CSS types.
