### ISSUE TITLE
IDL delta spec not included in webref

### ISSUE THREAD

**Issue by foolip** [w3c/webref#60]
https://github.com/w3c/browser-specs/blob/master/specs.json lists both https://www.w3.org/TR/css-transitions-1/ and https://drafts.csswg.org/css-transitions-2/, where the latter is a delta spec. It has some IDL:
https://drafts.csswg.org/css-transitions-2/#idl-index

However, that IDL is not included in webref.

**Comment by foolip** [comment]
The easiest for now would be if the IDL for both are included. Then WPT could work out if we should use both together, or just one of the files.

**Comment by tidoust** [comment]
Main question I have is around how these files need to be named.

Currently:
1. For IDL and CSS extracts, webref contains one file per spec series, named after the series shortname. For instance, [idl/css-animations.idl](https://github.com/w3c/webref/blob/master/ed/idl/css-animations.idl).
2. For other extracts (definitions, links, references), webref contains one file per spec, named after the spec shortname. For instance [dfns/css-animations-1.json](https://github.com/w3c/webref/blob/master/ed/dfns/css-animations-1.json) and [dfns/css-animations-2.json](https://github.com/w3c/webref/blob/master/ed/dfns/css-animations-2.json).

Should we switch to 2. for CSS and IDL?
Or should the extract of the "current" level/version still be named after the series shortname, while we would just add new extracts for cases where there are more recent levels/versions?

The ideal from a consistency perspective is to switch to 2. throughout Reffy, so that it generates the same filename for all types of extracts from the same spec. However, WPT would then have to decide which level/version of a spec it wants to use (the "current" level/version info is in browser-specs and used by Reffy to decide which content to put in the IDL extracts). That level/version also changes over time, so you'd probably want to have some mechanism in place to detect when the "current" version changes.

**Comment by foolip** [comment]
I think that naming only delta specs differently would be less of an inconvenience.

**Comment by tidoust** [comment]
IDL delta specs are now included in webref reports. This added [css-animations-2.idl](https://github.com/w3c/webref/blob/master/ed/idl/css-animations-2.idl) and [css-transitions-2](https://github.com/w3c/webref/blob/master/ed/idl/css-transitions-2.idl).
