### ISSUE TITLE
CSS Color and CSS Color 5 editorials now point to the same spec

### ISSUE THREAD

**Issue by pyoor** [w3c/webref#689]
I'm not sure if this is expected or not but the css-color.json and css-color-5.json both point to the same spec.  I assume that css-color.json should still point to css-color-4.  I wasn't sure if this is a problem with webref or a problem with browser-specs.

**Comment by tidoust** [comment]
That's not expected and actually currently breaks data curation (because curation includes a patch on css-color-4 that cannot be applied to css-color-5). Problem is that the level 4 spec claims that the ED is to be found at the version-less https://drafts.csswg.org/css-color/ URL. This indeed used to return level 4 but now returns level 5. I raised an issue on the CSS working group repo. I'll fix it in browser-specs in the meantime.

**Comment by tidoust** [comment]
Fixed in browser-specs (and redirect on draft CSS specs server should soon be fixed as well), so we're back on our feet in Webref.
