### ISSUE TITLE
CSS2 propdefs are being harvested with single-quotes around them

### ISSUE THREAD

**Issue by tabatkins** [w3c/webref#909]
Many (all?) of the property definitions coming from the CSS 2.1 spec are showing up in the database with single-quotes around them. For example, `background-position` shows up as both `background-position` (from Background & Borders) and `'background-position'` (from CSS 2). You can see these repeats in [the CSS Index doc](https://w3c.github.io/csswg-drafts/indexes/#properties).

I know these are already getting specially extracted; the quotes should be removed at the same time.

**Comment by tidoust** [comment]
I had left the quotes in because they are in the `title` attribute of the `<span>` element that defines them, so that seemed intended. The crawler now drops them. Let me know if there are other quirks that need to be applied!

One thing that is missing is the association between values and the properties for which they are defined, but the spec does not have `data-dfn-for` attributes and I don't see any easy way to create them automatically.

**Comment by tabatkins** [comment]
Thanks! I'll continue letting you know as I find quirks. 2.1's markup is.... interesting.
