### ISSUE TITLE
Malformed release of @webref/idl 3.29.0

### ISSUE THREAD

**Issue by queengooborg** [w3c/webref#918]
The release of `@webref/idl` 3.29.0 is malformed and is missing all of the IDL files.

**Comment by tidoust** [comment]
Thanks for the report, @queengooborg, and very sorry for the hiccup!

That was due to us renaming the `prepare` script a few days ago and forgetting about updating the release script to call the new script explicitly. Now fixed.

I published v3.30.0 of `@webref/idl` and flagged v3.29.0 as deprecated in npm.

**Comment by queengooborg** [comment]
Thank you -- can confirm that v3.30.0 is working as expected!
